import os
import csv
import time
import random

def generate_dummy_session(session_name="dummy_test", num_packets=200):
    base_dir = f"data/session_{session_name}"
    os.makedirs(base_dir, exist_ok=True)
    
    # 1. Generate RF Data
    rf_path = os.path.join(base_dir, "rf_data.csv")
    with open(rf_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp_monotonic_ms", "timestamp_device_ms", "source", "rssi", "rtt_ms", "mac_address", "ssid", "csi_amp", "csi_phase"])
        
        start_ts = time.monotonic() * 1000
        
        for i in range(num_packets):
            ts = start_ts + (i * 10) # 10ms intervals
            
            # Simulate 2 nodes
            if i % 2 == 0:
                src = "192.168.1.10" # Node A
                amp = [random.uniform(0.1, 1.0) for _ in range(64)]
            else:
                src = "192.168.1.11" # Node B
                amp = [random.uniform(0.1, 1.0) for _ in range(64)]
                
            writer.writerow([
                ts, ts, src, -50, 2, "AA:BB:CC:DD:EE:FF", "TestSSID", str(amp), str([0]*64)
            ])
            
    # 2. Generate Camera/Label Data
    # For training, we need 'labels.csv' (generated by process_all_data) OR we can mock it directly.
    # dataset.py looks for 'labels.csv' first, or 'pose_data.csv'? 
    # Actually process_all_data generates labels.csv.
    # Let's generate a mock labels.csv directly.
    
    lbl_path = os.path.join(base_dir, "labels.csv")
    with open(lbl_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp_monotonic_ms", "keypoints_flat", "presence", "location"])
        
        for i in range(num_packets):
            ts = start_ts + (i * 10)
            kp = [0.5] * 66 # 33 points * 2
            pres = 1.0
            loc = 0 # Room A
            
            writer.writerow([ts, str(kp), pres, loc])
            
    print(f"Generated dummy session at {base_dir}")

if __name__ == "__main__":
    generate_dummy_session()
